function G = computeG(x,y,z,t)
%computeG
%    G = computeG(X,Y,Z,T)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2024 16:31:22

t2 = y-1.0e+2;
t3 = z-8.0e+2;
t4 = t2.^2;
t5 = t3.^2;
G = [t+sqrt(t4+t5+(x-8.0e+3).^2);t+sqrt(t5+(t2-7.9e+3).^2+(x-1.0e+2).^2);t+sqrt((t2-1.9e+3).^2+(t3-4.2e+3).^2+(x-1.0e+3).^2);t+sqrt(t4+(t3-1.2e+3).^2+(x-2.0e+3).^2)];
end
